import "./globals.css";
import "antd/dist/antd.css";
import "./index.css";
import { Provider } from "react-redux";

export const metadata = {
  title: "Create Next Appma ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div></div>
        {children}
      </body>
    </html>
  );
}
